' Gambas module file

Public BatDebug As Battle



Public Sub InitUIStuff()
  BatDebug = New Battle
  BatDebug = BattleSequence.BatDebug
  
End


Public Sub EncounterMsg(FoeId As Integer)
  
  Dim Msg As String

  Msg = "You encountered " & MainDB.GetCharname(FoeId)
  Textbox(Msg)
  
End


Public Sub ClearSect()
  
  Draw.FillRect(8, 160, 240, 64, 0)
  
End



Public Sub SelectUI(Position As Integer)

  Dim ArrowY As Integer

  ClearSect()

  Draw.Rect(8, 160, 120, 64)

  Draw.Text("ATTACK", 24, 168)
  Draw.Text("E-SPELL", 24, 188)
  Draw.Text("DEFEND", 24, 208)

  ArrowY = 168 + ((Position - 1) * 20)

  Draw.Text(">", 12, ArrowY)

End

Public Sub SpellSelect()

  Dim i As Integer
  Dim X As Integer
  Dim SpellID As Integer
  Dim CurrentSpell As Spell

  ClearSect()

  For i = 0 To 3

    X = 12 + (i * 59)

    Draw.Rect(X, 160, 55, 64)

    SpellID = BatDebug.Hand[i]
    CurrentSpell = MainDB.GetSpell(SpellID)

    Draw.Text(CurrentSpell.Name, X + 4, 168)

  Next

End

Public Sub FoePortraitSingle(FoeId As Integer)
  
  Dim Path As String
  Dim img As Image
  Path = "images/foes/" & MainDB.GetCharname(FoeId) & ".png"
  img = Image.Load(Path)
  Draw.Image(img, 60, 10)

  
  
End



Public Sub Textbox(Text As String)

Dim Words As String[]
Dim Lines As String[]
Dim CurrentLine As String
Dim Word As String
Dim I As Integer



ClearSect()
Draw.Rect(8, 160, 240, 64)

Words = Split(Text, " ")
Lines = New String[]

For Each Word In Words

  If Len(CurrentLine) + Len(Word) + 1 > 30 Then
    Lines.Add(CurrentLine)
    CurrentLine = Word
  Else
    If CurrentLine = "" Then
      CurrentLine = Word
    Else
      CurrentLine &= " " & Word
    Endif
  Endif

Next

If CurrentLine <> "" Then Lines.Add(CurrentLine)

For I = 0 To Min(Lines.Count - 1, 2)
  Draw.Text(Str(Lines[I]), 20, 168 + (I * 20))
Next

End



 ' Gambas module file


