' Gambas module file



Public Struct Chara
  Name As String
  EsperType As String
  Power As Integer
  Defense As Integer
  NullMagic As Integer
  Speed As Integer
End Struct


Private db As Connection

Public Sub Initialize()

  
  db = New Connection
  
  db.Type = "sqlite3"
  db.Host = "/home/tmmartin/smepti"
  db.Name = "smepti.db"

  db.Open()

End

Public Sub GetCharname(charid As Integer) As String

  Dim result As Result

  result = db.Exec("SELECT name FROM charas WHERE id = &1", charid)

  Return result["name"]

End



Public Function GetSpell(spellid As Integer) As Spell

  Dim result As Result
  Dim spell As New Spell

  result = db.Exec("SELECT * FROM spells WHERE id = &1", spellid)

  If result = Null Then
    Return spell
  Endif

  result.MoveFirst()

  spell.Name = result["name"]
  spell.Power = result["power"]
  spell.Accuracy = result["accuracy"]
  spell.Effect = result["effect"]
  spell.Status = result["status"]
  spell.IsAlly = CBool(result["isally"])
  spell.IsGlobal = CBool(result["isglobal"])

  Return spell

End


Public Function GetChara(charaid As Integer) As Chara
  
  Dim result As Result
  Dim chara As Chara
  
  result = db.Exec("SELECT * FROM charas WHERE id = &1", charaid)
  
  chara.Name = result["name"]
  chara.EsperType = result["esper_type"]
  chara.Power = result["power"]
  chara.Defense = result["defense"]
  chara.NullMagic = result["nullmagic"]
  chara.Speed = result["speed"]
  
  Return chara
  
End

' Gambas module file
