' Gambas module file

Public Struct Spell
  Name As String
  Power As Integer
  Accuracy As Integer
  Effect As Integer
  Status As Integer
  IsAlly As Boolean
  IsGlobal As Boolean
  
End Struct' Gambas module file




Private db As Connection

Public Sub Initialize()

  
  db = New Connection
  
  db.Type = "sqlite3"
  db.Host = "/home/tmmartin/smepti"
  db.Name = "smepti.db"

  db.Open()

End

Public Sub GetCharname(charid As Integer) As String

  Dim result As Result

  result = db.Exec("SELECT name FROM charas WHERE id = &1", charid)

  Return result["name"]

End



Public Sub GetSpell(spellid As Integer) As Spell
  
  Dim result As Result
  Dim spell As Spell
  result = db.Exec("SELECT * FROM spells where id = &1", spellid)
  spell.Name = result["name"]
  spell.Power = result["power"]
  spell.Accuracy = result["accuracy"]
  spell.Effect = result["effect"]
  spell.IsAlly = CBool(result["isally"])
  spell.IsGlobal = CBool(result["isglobal"])
  
  Return spell
  
End


' Gambas module file
