' Gambas module file

Private $hWindow As Window
Private FoeID As Integer
Private CurrMenu As Integer
Private PosArrow As Integer
Private IsInitDone As Boolean


Public Sub Main()

  $hWindow = New Window As "Window"
  FoeID = 2
  

  With $hWindow
    .Resize(256, 240)
    .Resizable = False
    .Show
    .FrameRate = 60
    $hWindow.FullScreen = Not $hWindow.FullScreen

    MainDB.Initialize
   
    BattleSequence.Init()
    BattleUI.InitUIStuff

    IsInitDone = False
    PosArrow = 1
    CurrMenu = 1
  End With

End


Public Sub Window_Draw()

  Dim H As Integer

  H = Font.DefaultHeight

  Draw.Clear
  Draw.Font.Size = H

  If IsInitDone = False Then

    BattleSequence.Initial_Msg(FoeID)

  Else

    If CurrMenu = 2 Then
      BattleSequence.Show_Spells(FoeID)

    Else If CurrMenu = 1 Then
      BattleSequence.Show_Menu(FoeID, PosArrow)

    Endif

  Endif

End


Public Sub Window_KeyPress()

  Select Case Key.Code

    Case Key.Return

      If IsInitDone = False Then

        IsInitDone = True

      Else

        Select Case PosArrow

          Case 1
            CurrMenu = 2

          Case 2
            ' Segunda opción del menú principal

        End Select

      Endif


    Case Key.Up

      If IsInitDone = True And CurrMenu = 1 Then

        PosArrow -= 1

        If PosArrow < 1 Then
          PosArrow = 2
        Endif

      Endif


    Case Key.Down

    If IsInitDone = True And CurrMenu = 1 Then

    PosArrow += 1

    If PosArrow > 3 Then
      PosArrow = 1
    Endif

  Endif


    Case Key.Backspace

      If IsInitDone = True Then
        CurrMenu = 1
      Endif


    Case Key.Esc

      $hWindow.Close

  End Select

End