' Gambas module file

Private $hWindow As Window
Private FoeID As Integer
Private $SelectedUI As Boolean



Public Sub Main()


  
  $hWindow = New Window As "Window"
  FoeID = 2
  With $hWindow
    .Resize(256, 240)
    .Resizable = False
    .Show
    .FrameRate = 60
    $hWindow.FullScreen = Not $hWindow.FullScreen
    MainDB.Initialize
  End With 
  
End

Public Sub Window_Draw()

  Dim H As Integer

  H = Font.DefaultHeight

  Draw.Clear
  Draw.Font.Size = H

  BattleUI.EncounterMsg(FoeID)
  BattleUI.FoePortraitSingle(FoeID)

  If $SelectedUI Then
    BattleUI.SelectUI()
  Endif

End

Public Sub Window_KeyPress()

  Select Case Key.Code

    Case Key.F1
      $SelectedUI = True

    Case Key.F2
      $SelectedUI = False

    Case Key.Esc
      $hWindow.Close

  End Select



End